version: '3'
networks:
  default:
    external:
      name: stackl
  stackl_bridge:
    external:
      name: stackl_bridge
services:
  stackl-rest:
    restart: always
    image: stackl_app
    container_name: stackl_app
    networks:
      - stackl_bridge
    volumes:
      - /example_database/:/lfs_test_store/
    ports:
      - 8080:80
      - 8888:8888
    environment:
      - STACKL_STORE=LFS
      - STACKL_TASK_BROKER=Custom
      - STACKL_AGENT_BROKER=Local
      - STACKL_AGENT_HOST=stackl-agent:50051
      - GRPC_VERBOSITY="DEBUG"
      - STACKL_LOGPATH=/var/log/stackl.log
      - STACKL_MESSAGE_CHANNEL=RedisSingle
      - STACKL_STACKLRESTHOST=stackl-rest
      - STACKL_STACKLRESTPORT=80
      - STACKL_REDISSENTINELHOST=stackl-redis
      - TCP_PORTS=80
      - SERVICE_PORTS=80
      - STACKL_PKIHOST=stackl.stackl.io
      - STACKL_PKIPORT=8443
      - STACKL_PKICA=intermCA
      - STACKL_REDIS_HOST=stackl-redis
      - LOGLEVEL=DEBUG
  stackl-worker:
    restart: always
    image: stackl_worker
    networks:
      - stackl_bridge
    stdin_open: true
    tty: true
    volumes:
      - /example_database/:/lfs_test_store/
    depends_on:
      - stackl-rest
      - stackl-redis
    ports:
      - 9999:9999
    environment:
      - STACKL_STORE=LFS
      - STACKL_TASK_BROKER=Custom
      - STACKL_AGENT_BROKER=Local
      - STACKL_AGENT_HOST=stackl-agent:50051
      - GRPC_VERBOSITY="DEBUG"
      - STACKL_LOGPATH=/var/log/stackl.log
      - STACKL_MESSAGE_CHANNEL=RedisSingle
      - STACKL_STACKLRESTHOST=stackl-rest
      - STACKL_STACKLRESTPORT=80
      - STACKL_REDISSENTINELHOST=stackl-redis
      - STACKL_ROLE=worker
      - STACKL_REDIS_HOST=stackl-redis
      - TCP_PORTS=8888
      - LOGLEVEL=DEBUG
  stackl-redis:
    restart: always
    image: redis:5.0.5
    networks:
      - stackl_bridge
  stackl-agent:
    restart: always
    image: local_agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - stackl_bridge
    ports:
      - 8889:8889
      - 50051:50051
    environment:
      - STACKL_HOST=stackl-rest:80
      - HOST_MACHINE=stackl-agent
      - TAGS=['common']
      - TENANT=