[build]
publish = "docs/website/public"
command = "make docs-clean docs-generate docs-production-build"

[build.environment]
HUGO_VERSION = "0.56.1"

[context.deploy-preview]
command = "make docs-clean docs-generate docs-preview-build"

[context.branch-deploy]
command = "make docs-clean docs-generate docs-preview-build"

[dev]
# "netlify dev" will serve the static content using netlify locally
# with all the redirects and other netlify specific rules in place.
publish = "docs/website/public"
